create table EMPRESA(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE NVARCHAR(200) UNIQUE NOT NULL,
);

CREATE TABLE PRODUCTO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE NVARCHAR(200) NOT NULL,
	CANTIDAD INT NOT NULL,
	EMPRESAID INT, 
    FOREIGN KEY (EMPRESAID) REFERENCES EMPRESA(ID)

)

INSERT INTO EMPRESA(NOMBRE)
VALUES
	('FROMSOFTWARE'),
	('BLIZZARD'),
	('CAPCOM')
	

	INSERT INTO PRODUCTO(NOMBRE,CANTIDAD,EMPRESAID)
	VALUES
	('DARKSOULS',10,1),
	('ELDEN RING',20,1),
	('SEKIRO',5,1),
	('WORLD OF WARCRAFT',50,2),
	('OVERWATCH',3,2),
	('DIABLO',20,2),
	('RESIDENT EVIL',60,3),
	('DEVIL MAY CRY',7,3),
	('MONSTER HUNTER',20,3)

	select * from PRODUCTO
	inner join EMPRESA
	on PRODUCTO.EMPRESAID = EMPRESA.ID
	where EMPRESA.NOMBRE = 'FROMSOFTWARE'

	SELECT * FROM EMPRESA ORDER BY ID
